export const projectStructureMock = {
  project_name: "Project 1",
  project_author: "Rafael Buzón Urbano",
  project_url: "https://projecturl.com/project1",
  files: [
    "file1.txt",
    "file2.png",
    "file3.jpg",
    "file4.tsx",
    "file5.gif",
    "file6.ts",
  ],
  folder: {
    files: [
      "file1.gif",
      "file2.gif",
      "file3.css",
      "file4.jpg",
      "file5.jpg",
      "file6.ts",
    ],
    folder: {
      files: [
        "file1.js",
        "file2.php",
        "file3.py",
        "file4.txt",
        "file5.c",
        "file6.c",
        "file7.txt",
        "file8.gif",
      ],
      folder: {
        files: [
          "file1.h",
          "file2.c",
          "file3.tsx",
          "file4.jpg",
          "file5.jpg",
          "file6.jpg",
          "file7.jpg",
          "file8.jpg",
          "file9.jpg",
          "file10.jpg",
          "file11.jpg",
          "file12.js",
          "file13.js",
          "file14.py",
        ],
        folder: {
          files: [
            "file1.ts",
            "file2.tsx",
            "file3.jpg",
            "file4.css",
            "file5.css",
            "file6.css",
            "file7.php",
            "file8.py",
          ],
          folder: {
            files: [
              "file1.php",
              "file2.py",
              "file3.h",
              "file4.py",
              "file5.py",
              "file6.h",
            ],
          },
        },
      },
    },
  },
};
